# Generated by Django 4.0.6 on 2022-07-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.TextField(default=0),
        ),
    ]
