# Generated by Django 4.0.6 on 2022-07-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0006_rename_text_post_body_rename_created_dt_post_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update',
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
